### ISSUE TITLE
Error: Object has not member json when used with kms client

### ISSUE THREAD

**Issue by xescuder** [grafana/xk6-webcrypto#50]
Hi. I've a script that uses the KMSClient to generate a data key from AWS:

```
  import { AWSConfig, KMSClient } from 'https://jslib.k6.io/aws/0.8.0/kms.js';

  export function setup() {
    return {
        dataKey: kms.generateDataKey(keyAlias, 32)
     };

```

All script works fine and I am able to send and generate correctly everything.

If I add the import:

`import { crypto } from "k6/experimental/webcrypto";`

The code fails with:
`
ERRO[0003] TypeError: Object has no member 'json'
        at value (webpack://k6-jslib-aws/./src/internal/kms.ts:118:39(93))
        at setup (file:///Users/escuderx/Projects/nst_performance_testing/script.js:73:70(15))  hint="script exception"
`

Can you give me some advice? I don't see why this library is impacting the code, and not the others.

**Comment by olegbespalov** [comment]
Hi @xescuder 

I'm sorry for not getting back to you sooner.

I believe you faced the issue that was fixed in https://github.com/grafana/xk6-webcrypto/pull/56

Let me know if that's still reproducible with the latest version of the module.

**Comment by olegbespalov** [comment]
I'm closing the issue right now, feel free to re-open it if it's still the case
